stages:
  - install
  - test
  - build

cache:
  paths:
    - ~/.poetry/virtualenvs/
  key: $CI_COMMIT_REF_SLUG

install:
  stage: install
  script:
    - poetry install
  tags:
    - python

test:
  stage: test
  script:
    - poetry run pytest
  tags:
    - python

build:
  stage: build
  script:
    - poetry build
  artifacts:
    paths:
      - dist/*
  tags:
    - python
